version: "3.9"

services:

  app_test:
    build: .
    container_name: app_test
    command: ['./start.sh']
    #volumes:
      #- ./task_db.sqlite3:/test_task/task_db.sqlite3
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: "db_welbex"
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


volumes:
  data:
