version: "3.9"

services:

  db:
    image: postgres
    container_name: "db_welbex"
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
      - "4777:5432"


volumes:
  data:
